export BASE = helm
export CHART = cert-manager
export NAMESPACE = cert-manager
export REPO = jetstack
export URL = https://charts.jetstack.io
export VERSION = v1.14.3

include ../Makefile

seal:
_PHONY: seal
